version: "3"

services:
  delpipes:
    image: alpine
    volumes:
      - named_pipes:/app_data
    command:
      - sh
      - -c
      - echo Doing nothing
      #- rm -f /app_data/* && ls /app_data

  netcom_forwarder:
    depends_on:
      - init
      - rabbitmq
    build: netcom_forwarder
    volumes:
      - named_pipes:/app_data
    command:
      - /app_data/out
      - /app_data/in

  init:
    image: ubuntu
    volumes:
      - ./init:/app_init
      - named_pipes:/app_data
    command:
      #- bash
      - /bin/bash
      - /app_init/init_named_pipes.sh

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbithost
    ports:
      - "8080:15672"
      - 15674:15674
    #networks:
    #  rabbit:
    #    aliases:
    #      - rabbithost

  zombie:
    depends_on:
      - init
    build: zombie
    #external_links:
    #  - rabbitmq:rabbithost
    volumes:
      - named_pipes:/app_data
    command:
      - /app_data/in
      - /app_data/out

volumes:
  named_pipes:

#networks:
#  default:
#    external:
#      name: containers_rabbit
