version: '2'

services:

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbithost
    ports:
      - "8080:15672"
#      - 15674:15674
    networks:
      rabbit:
        aliases:
          - rabbithost

  web_server:
    build: web_server
    image: web_server
    ports:
      - "80:80"
    volumes:
      - ../source/front_end/html/client:/usr/share/nginx/html
    #links:
    #  - socketio_backend

  nodejs:
    build: nodejs
    image: nodejs
    volumes:
      - ../source:/mnt/src

networks:
  rabbit: