version: '2'
services:

  zookeeper:
    build: .
    image: kafka-zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      zoo_kafka:
        aliases:
          - zookeeper
    command:
    - /app/kafka/bin/zookeeper-server-start.sh
    - /app/kafka/config/zookeeper.properties

  kafka:
    image: kafka-zookeeper
    container_name: kafka
    links:
    - zookeeper:zoo
    ports:
    - "9092:9092"
    networks:
      zoo_kafka:
        aliases:
          - kafka
    command:
      - /app/start-kafka.sh

networks:
  zoo_kafka:
