version: '2'
services:

  zookeeper:
    build: kafka-zookeeper
    image: kafka-zookeeper
    #container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      zoo_kafka:
        aliases:
          - zookeeper
    command:
    - /app/kafka/bin/zookeeper-server-start.sh
    - /app/kafka/config/zookeeper.properties

  kafka:
    image: kafka-zookeeper
    #container_name: kafka
    links:
    - zookeeper:zoo
    ports:
    - "9092:9092"
    networks:
      zoo_kafka:
        aliases:
          - kafka
    command:
      - /app/start-kafka.sh

  socketio_backend:
    build: socketio
    image: socketio
    #container_name: socketio
    #links:
    #- kafka
    ports:
    - "10123:10123"
    networks:
      zoo_kafka:
        aliases:
          - socketio
    #command:
      #- mvn
      #- exec:java

networks:
  zoo_kafka:
