version: "3"

services:
  zombie:
    image: ${PRIVATE_DOCKER_REGISTRY}/zombie-light
    volumes:
      - named_pipes:/app_data
    command:
      - /app_data/in
      - /app_data/out

  zombie-netcom-forwarder:
    networks:
      - netcom
    image: netcom-forwarder
    volumes:
      - named_pipes:/app_data
    command:
      - /app_data/out
      - /app_data/in
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: pw
      
volumes:
  named_pipes:

networks:
  netcom:
    external: true
