version: '2'

services:

  zookeeper:
    build: kafka-zookeeper
    image: kafka-zookeeper
    #container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      zoo_kafka:
        aliases:
          - zookeeper
    command:
    - /app/kafka/bin/zookeeper-server-start.sh
    - /app/kafka/config/zookeeper.properties

  kafka:
    image: kafka-zookeeper
    #container_name: kafka
    links:
    - zookeeper:zoo
    ports:
    - "9092:9092"
    networks:
      zoo_kafka:
        aliases:
          - kafka
    command:
      - /app/start-kafka.sh

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbithost
    ports:
      - 8080:15672
    networks:
      rabbit:
        aliases:
          - rabbithost

  web_server:
    build: web_server
    image: web_server
    ports:
      - "80:80"
    volumes:
      - ../source/front_end/html/client:/usr/share/nginx/html
    #links:
    #  - socketio_backend

  nodejs:
    build: nodejs
    image: nodejs
    volumes:
      - ../source:/mnt/src

networks:
  zoo_kafka:
  rabbit: