version: "3"

services:
  delpipes:
    image: alpine
    volumes:
      - named_pipes:/app_data
    command:
      - sh
      - -c
      - echo Doing nothing
      #- rm -f /app_data/* && ls /app_data

  netcom_forwarder:
    depends_on:
      - init
    networks:
      - netcom
    image: netcom_forwarder
    volumes:
      - named_pipes:/app_data
    command:
      - /app_data/out
      - /app_data/in

  init:
    image: ubuntu
    volumes:
      - ./init:/app_init
      - named_pipes:/app_data
    command:
      - /bin/bash
      - -c
      - /app_init/init_named_pipes.sh
      
  app:
    depends_on:
      - netcom_forwarder
    build: .
    volumes:
      - named_pipes:/app_data
    command:
      - /app_data/in
      - /app_data/out

volumes:
  named_pipes:

networks:
  netcom:
    external: true