version: "3"

services:
  map_info_producer:
    build: .
    volumes:
      - named_pipes:/app_data
    command:
      - /app_data/in
      - /app_data/out

  map_info_producer_netcom_forwarder:
    networks:
      - netcom
    image: netcom-forwarder
    volumes:
      - named_pipes:/app_data
    command:
      - /app_data/out
      - /app_data/in

volumes:
  named_pipes:

networks:
  netcom:
    external: true