apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zombie
  labels:
    app: zombie
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zombie
    spec:
      containers:
      - name: app
        image: eu.gcr.io/gridwalls2/zombie-light:latest
        args: ["/app_data/in", "/app_data/out"]
        imagePullPolicy: Always
        volumeMounts:
          - name: named-pipes
            mountPath: /app_data
      - name: netcom-forwarder
        image: eu.gcr.io/gridwalls2/netcom-forwarder:latest
        args: ["/app_data/out", "/app_data/in", "fair-blackbird-rabbitmq"]
        imagePullPolicy: Always
        volumeMounts:
          - name: named-pipes
            mountPath: /app_data
        env:
        - name: RABBITMQ_USERNAME
          value: "user"
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fair-blackbird-rabbitmq
              key: rabbitmq-password
      volumes:
        - name: named-pipes
          emptyDir: {}
