# Source: zombie-light/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ordered-turkey-zombie-light
  labels:
    app: zombie-light
    chart: zombie-light-0.1.0
    release: ordered-turkey
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zombie-light
        release: ordered-turkey
    spec:
      containers:
      - name: app
        image: "eu.gcr.io/gridwalls2/netcom-forwarder:latest"
        args: ["/named_pipes/in", "/named_pipes/out"]
        imagePullPolicy: Always
        volumeMounts:
        - name: named-pipes
          mountPath: /named_pipes
        resources:
      - name: netcom-forwarder
        image: "eu.gcr.io/gridwalls2/zombie-light:latest"
        args: ["/named_pipes/out", "/named_pipes/in", "fair-blackbird-rabbitmq"]
        imagePullPolicy: Always
        volumeMounts:
        - name: named-pipes
          mountPath: /named_pipes
        env:
        - name: RABBITMQ_USERNAME
          value: "user"
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fair-blackbird-rabbitmq
              key: rabbitmq-password
      volumes:
        - name: named-pipes
          emptyDir: {}
