version: "3"

services:
  map-info-producer:
    image: ${PRIVATE_DOCKER_REGISTRY}/map-info-producer
    volumes:
      - named_pipes:/app_data
    command:
      - /app_data/in
      - /app_data/out

  map-info-producer-netcom-forwarder:
    networks:
      - netcom
    image: netcom-forwarder
    volumes:
      - named_pipes:/app_data
    command:
      - /app_data/out
      - /app_data/in

volumes:
  named_pipes:

networks:
  netcom:
    external: true