version: '2'

services:

  concourse-db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database
    #volumes:
    #    - ./database:/database
    #networks:
    #  - concourse

  concourse-web:
    image: concourse/concourse
    links:
      - concourse-db
    command: web
    ports:
      - "8081:8080"
    volumes:
      - ./keys/web:/concourse-keys
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: changeme
      CONCOURSE_EXTERNAL_URL: "http://127.0.0.1:8081"
      CONCOURSE_POSTGRES_DATA_SOURCE: |
        postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable
    #networks:
    #  - concourse

  concourse-worker:
    image: concourse/concourse
    privileged: true
    links:
      - concourse-web
    command: worker
    volumes:
      - ./keys/worker:/concourse-keys
    environment:
      CONCOURSE_TSA_HOST: concourse-web
    #networks:
    #  - concourse

#networks:
#  concourse:
