---
jobs:
- name: simple2app
  public: true
  plan:
  - task: someTask
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: buildserver
      run:
        path: buildserver/mytest/test.sh
